.PHONY: all go java python tcl clean

all: go java python tcl

go:
	$(MAKE) -C go

java:
	$(MAKE) -C java

python:
	$(MAKE) -C python

tcl:
	$(MAKE) -C tcl

clean:
	$(MAKE) -C go clean
	$(MAKE) -C java clean
	$(MAKE) -C python clean
	$(MAKE) -C tcl clean
